settings:
  username: JeremyZzzz
  commit_msg: "Update README with the recent activity"
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  date:
    text: "Last Updated: {DATE} (GMT)"
